# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ashish Tibrewal
email: ashish.tibrewal@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my corner of the world wide web. I am a 4th year
  Computer Science & Electronics student at the University of
  Bristol.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
linkedin_username: tibrewalashish
github_username:  ashishtibrewal

# Build settings
markdown: kramdown
